name: binance_api_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_pw_validator: ^1.4.2
  flutter_beep: ^1.0.0
  blurry_modal_progress_hud: ^1.0.3
  dropdown_search: ^5.0.2
  email_validator: ^2.0.1
  equatable: ^2.0.3
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9 
  get_it: ^7.2.0
  line_icons: ^2.0.1
  logger: ^1.1.0
  provider: ^6.0.3
  intl: any
  shared_preferences: ^2.0.15
  stacked: ^3.2.3
  flutter_typeahead: ^4.2.0
  iconamoon: ^0.0.3
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.11
  table_calendar: ^3.0.8
  flutter_launcher_icons: ^0.13.1
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  sqflite: ^2.3.3
  path: ^1.9.0
  fl_chart: ^0.67.0
  web_socket_channel: ^2.4.5
  connectivity_plus: ^2.3.0
  qr_flutter: ^4.1.0
  excel: ^2.0.5
  path_provider: ^2.1.5
  qr_code_scanner: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/icono4.png"
  adaptative_icon_background: "assets/img/background.png"
  adaptative_icon_foreground: "assets/img/background.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/

